version: "3.7"

services:
  server:
    build: ""
    volumes:
      - $WWW:/www
    environment:
      - TESTCASE=$TESTCASE
  client:
    build: ""
    volumes:
      - $DOWNLOADS:/downloads
    environment:
      - TESTCASE=$TESTCASE
      - REQUESTS=$REQUESTS
